FROM n8nio/n8n

ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=andr974j
ENV N8N_BASIC_AUTH_PASSWORD=Nze87gga

ENV WEBHOOK_URL=https://din-host.render.com/
ENV N8N_HOST=0.0.0.0
ENV N8N_PORT=5678

EXPOSE 5678

ENTRYPOINT ["tini", "--"]
CMD ["n8n"]
