services:
  - type: web
    name: n8n
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: "minbruger"
      - key: N8N_BASIC_AUTH_PASSWORD
        value: "hemmelig123"
      - key: N8N_HOST
        value: "din-host.render.com"
      - key: N8N_PORT
        value: "5678"
      - key: WEBHOOK_URL
        value: "https://din-host.render.com/"